import type { User, Team, Project, Task } from "./types"

// 简笔画风格的头像 URL (使用 DiceBear API 生成简单头像)
export const mockUsers: User[] = [
  {
    id: "1",
    name: "张三",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Zhang",
    email: "zhangsan@example.com",
  },
  {
    id: "2",
    name: "李四",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Li",
    email: "lisi@example.com",
  },
  {
    id: "3",
    name: "王五",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Wang",
    email: "wangwu@example.com",
  },
  {
    id: "4",
    name: "赵六",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Zhao",
    email: "zhaoliu@example.com",
  },
  {
    id: "5",
    name: "钱七",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Qian",
    email: "qianqi@example.com",
  },
  {
    id: "6",
    name: "孙八",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sun",
    email: "sunba@example.com",
  },
]

export const mockTeams: Team[] = [
  {
    id: "team-1",
    name: "产品研发团队",
    description: "负责核心产品开发",
    color: "#3b82f6",
    memberIds: ["1", "2", "3"],
    createdAt: new Date("2024-01-01"),
  },
  {
    id: "team-2",
    name: "市场营销团队",
    description: "负责市场推广和品牌建设",
    color: "#10b981",
    memberIds: ["4", "5"],
    createdAt: new Date("2024-01-15"),
  },
  {
    id: "team-3",
    name: "设计团队",
    description: "负责UI/UX设计",
    color: "#f59e0b",
    memberIds: ["6", "2"],
    createdAt: new Date("2024-02-01"),
  },
]

export const mockProjects: Project[] = [
  {
    id: "1",
    name: "日历系统开发",
    description: "开发新一代日历管理系统",
    color: "#3b82f6",
    memberIds: ["1", "2", "3"],
    teamId: "team-1",
    createdAt: new Date("2024-01-10"),
  },
  {
    id: "2",
    name: "移动应用",
    description: "开发配套移动应用",
    color: "#8b5cf6",
    memberIds: ["1", "3"],
    teamId: "team-1",
    createdAt: new Date("2024-02-01"),
  },
  {
    id: "3",
    name: "品牌推广活动",
    description: "Q1季度品牌推广",
    color: "#10b981",
    memberIds: ["4", "5"],
    teamId: "team-2",
    createdAt: new Date("2024-01-20"),
  },
  {
    id: "4",
    name: "UI重构项目",
    description: "全站UI视觉升级",
    color: "#f59e0b",
    memberIds: ["6", "2"],
    teamId: "team-3",
    createdAt: new Date("2024-02-10"),
  },
  {
    id: "5",
    name: "个人学习计划",
    description: "个人技能提升",
    color: "#ec4899",
    memberIds: ["1"],
    createdAt: new Date("2024-03-01"),
  },
]

// 生成一些示例任务 (使用当前月份 2025-11)
export const mockTasks: Task[] = [
  // 张三的任务 (当前用户)
  {
    id: "task-1",
    title: "系统架构设计",
    description: "设计日历系统的整体架构",
    startDate: new Date("2025-11-13"),
    endDate: new Date("2025-11-15"),
    startTime: "09:00",
    type: "daily",
    projectId: "1",
    userId: "1",
  },
  {
    id: "task-2",
    title: "团队周会",
    description: "每周团队同步会议",
    startDate: new Date("2025-11-14"),
    endDate: new Date("2025-11-14"),
    startTime: "14:00",
    endTime: "15:00",
    type: "meeting",
    projectId: "1",
    userId: "1",
  },
  {
    id: "task-3",
    title: "前端开发",
    description: "实现日历组件",
    startDate: new Date("2025-11-16"),
    endDate: new Date("2025-11-20"),
    startTime: "09:00",
    type: "daily",
    projectId: "1",
    userId: "1",
  },
  {
    id: "task-13",
    title: "代码评审",
    description: "Review团队成员的PR",
    startDate: new Date("2025-11-14"),
    endDate: new Date("2025-11-14"),
    startTime: "10:00",
    endTime: "11:00",
    type: "meeting",
    projectId: "1",
    userId: "1",
  },
  {
    id: "task-14",
    title: "性能优化",
    description: "优化页面加载速度",
    startDate: new Date("2025-11-18"),
    endDate: new Date("2025-11-19"),
    startTime: "09:00",
    type: "daily",
    projectId: "1",
    userId: "1",
  },
  {
    id: "task-15",
    title: "移动端适配",
    description: "完成移动端响应式布局",
    startDate: new Date("2025-11-21"),
    endDate: new Date("2025-11-23"),
    startTime: "09:00",
    type: "daily",
    projectId: "2",
    userId: "1",
  },
  {
    id: "task-16",
    title: "技术分享会",
    description: "分享React最佳实践",
    startDate: new Date("2025-11-22"),
    endDate: new Date("2025-11-22"),
    startTime: "15:00",
    endTime: "16:30",
    type: "meeting",
    projectId: "1",
    userId: "1",
  },
  {
    id: "task-17",
    title: "个人学习",
    description: "学习TypeScript高级特性",
    startDate: new Date("2025-11-25"),
    endDate: new Date("2025-11-27"),
    startTime: "20:00",
    type: "daily",
    projectId: "5",
    userId: "1",
  },
  {
    id: "task-18",
    title: "文档编写",
    description: "编写项目技术文档",
    startDate: new Date("2025-11-15"),
    endDate: new Date("2025-11-15"),
    startTime: "14:00",
    type: "daily",
    projectId: "1",
    userId: "1",
  },
  
  // 李四的任务
  {
    id: "task-4",
    title: "API开发",
    description: "开发后端API接口",
    startDate: new Date("2025-11-13"),
    endDate: new Date("2025-11-17"),
    startTime: "09:00",
    type: "daily",
    projectId: "1",
    userId: "2",
  },
  {
    id: "task-5",
    title: "UI设计评审",
    description: "参与UI设计方案评审",
    startDate: new Date("2025-11-15"),
    endDate: new Date("2025-11-15"),
    startTime: "10:00",
    endTime: "11:30",
    type: "meeting",
    projectId: "4",
    userId: "2",
  },
  
  // 王五的任务
  {
    id: "task-6",
    title: "数据库设计",
    description: "设计数据库表结构",
    startDate: new Date("2025-11-14"),
    endDate: new Date("2025-11-16"),
    startTime: "09:00",
    type: "daily",
    projectId: "1",
    userId: "3",
  },
  {
    id: "task-7",
    title: "移动端原型",
    description: "制作移动端交互原型",
    startDate: new Date("2025-11-17"),
    endDate: new Date("2025-11-19"),
    startTime: "09:00",
    type: "daily",
    projectId: "2",
    userId: "3",
  },
  
  // 赵六的任务
  {
    id: "task-8",
    title: "社交媒体运营",
    description: "准备本周社交媒体内容",
    startDate: new Date("2025-11-13"),
    endDate: new Date("2025-11-19"),
    startTime: "09:00",
    type: "daily",
    projectId: "3",
    userId: "4",
  },
  {
    id: "task-9",
    title: "合作伙伴会议",
    description: "与潜在合作伙伴洽谈",
    startDate: new Date("2025-11-16"),
    endDate: new Date("2025-11-16"),
    startTime: "14:00",
    endTime: "16:00",
    type: "meeting",
    projectId: "3",
    userId: "4",
  },
  
  // 钱七的任务
  {
    id: "task-10",
    title: "市场调研报告",
    description: "撰写Q1市场调研报告",
    startDate: new Date("2025-11-15"),
    endDate: new Date("2025-11-18"),
    startTime: "09:00",
    type: "daily",
    projectId: "3",
    userId: "5",
  },
  
  // 孙八的任务
  {
    id: "task-11",
    title: "视觉设计",
    description: "完成首页视觉设计",
    startDate: new Date("2025-11-13"),
    endDate: new Date("2025-11-17"),
    startTime: "09:00",
    type: "daily",
    projectId: "4",
    userId: "6",
  },
  {
    id: "task-12",
    title: "年假",
    description: "休假",
    startDate: new Date("2025-11-20"),
    endDate: new Date("2025-11-22"),
    type: "vacation",
    projectId: "4",
    userId: "6",
  },
]
